- name: Download binaries
  command: wget --continue -P /var/tmp http://dev.mysql.com/get/Downloads/MySQL-Cluster-7.3/mysql-cluster-gpl-7.3.4-linux-glibc2.5-x86_64.tar.gz
- name: Clean up old folders
  shell: rm -fR /usr/local/mysql-cluster-gpl-7.3.4-linux-glibc2.5-x86_64/
- name: Extract binaries
  command: tar -C /usr/local -xzf /var/tmp/mysql-cluster-gpl-7.3.4-linux-glibc2.5-x86_64.tar.gz creates=/usr/local/mysql-cluster-gpl-7.3.4-linux-glibc2.5-x86_64
- name: Move data
  shell: mv /usr/local/mysql-cluster-gpl-7.3.4-linux-glibc2.5-x86_64/data/* /usr/local/mysql/data creates=/usr/local/mysql/data/test
- name: Remove old folder
  shell: rm -fR /usr/local/mysql-cluster-gpl-7.3.4-linux-glibc2.5-x86_64/data/
- name: Rename mysql folder
  shell: mv /usr/local/mysql-cluster-gpl-7.3.4-linux-glibc2.5-x86_64/* /usr/local/mysql/ creates=/usr/local/mysql/bin
- name: Create mysql group
  group: name=mysql system=yes
- name: Create mysql user
  user: name=mysql system=yes createhome=no group=mysql
- name: Install nbd binaries
  command: install /usr/local/mysql/bin/ndbd /usr/local/bin/ndbd creates=/usr/local/bin/ndbd
- name: Install config
  template: src=my.cnf dest=/etc/my.cnf
- name: Install init file
  copy: src=ndbd.init dest=/etc/init.d/ndbd mode=775
- name: Activate init file
  service: name=ndbd enabled=yes
- name: Initialize ndbd
  command: /usr/local/bin/ndbd --initial creates=/usr/local/mysql/data/ndb_*_fs/
